### ISSUE TITLE
Exception with pulling latest image for flow

### ISSUE THREAD

**Issue by yilativ** [totaljs/flow#113]
![image](https://github.com/totaljs/flow/assets/1034910/57c8e951-b9af-46ae-8614-d6981b3784d0)

After I pulled latest flow image with the following compose, the above happens and I cannot create any workflows: 

```YAML
  flow:
    container_name: flow
    volumes:
      - flow:/www/
    image: totalplatform/flow:latest
    ports:
      - 8102:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
```

When I drag and drop, nothing happens. This is a completely fresh setup. 

Here's the log from the container running the image: 
```
2024-03-18T01:09:54.571107084Z 
2024-03-18T01:09:54.571173886Z > flow@10.0.0 start
2024-03-18T01:09:54.571184386Z > node index.js 8000
2024-03-18T01:09:54.571189587Z 
2024-03-18T01:09:55.057571304Z > DEBUG PID: 18 (v5)
2024-03-18T01:09:55.533904473Z --------------------- BUNDLING ---------------------
2024-03-18T01:09:55.543742214Z ----- app.bundle
2024-03-18T01:09:55.955951466Z Done: 420.903ms
2024-03-18T01:09:56.465859697Z ====================================================
2024-03-18T01:09:56.465892098Z PID           : 25
2024-03-18T01:09:56.465899198Z Node.js       : v19.9.0
2024-03-18T01:09:56.466133506Z Total.js      : v5000
2024-03-18T01:09:56.466144007Z OS            : linux 5.15.133.1-microsoft-standard-WSL2
2024-03-18T01:09:56.466545720Z Memory        : 10.01 MB / 17.67 MB
2024-03-18T01:09:56.466808230Z User          : root
2024-03-18T01:09:56.466826230Z ====================================================
2024-03-18T01:09:56.466842131Z Name          : Total.js Flow v10
2024-03-18T01:09:56.466921733Z Version       : 1.0.0
2024-03-18T01:09:56.468170577Z Date (utc)    : 2024-03-18 01:09:55
2024-03-18T01:09:56.468466887Z Mode          : debug
2024-03-18T01:09:56.468506288Z Compiled      : 15 files (520ms)
2024-03-18T01:09:56.468550890Z ====================================================
2024-03-18T01:09:56.468563790Z Directory     : /www
2024-03-18T01:09:56.468652593Z node_modules  : /www/node_modules/
2024-03-18T01:09:56.468668094Z ====================================================
2024-03-18T01:09:56.468675394Z 
2024-03-18T01:09:56.468718696Z http://0.0.0.0:8000/
2024-03-18T01:09:56.468741696Z 
2024-03-18T01:10:02.619291246Z ERROR ======= 2024-03-18 01:10:02: COMPONENTATOR ---> Error: aborted 
2024-03-18T02:46:26.951834819Z FlowStream auto-restart: users_import_file (exit code: 0)
2024-03-18T03:17:25.682204548Z ERROR ======= 2024-03-18 03:17:25: TypeError: Cannot convert undefined or null to object
2024-03-18T03:17:25.682487850Z     at MAKEFLOWSTREAM.flow.export2 (/www/node_modules/total5/flow-flowstream.js:1932:17)
2024-03-18T03:17:25.682515150Z     at Timeout.saveforce (/www/node_modules/total5/flow-flowstream.js:1954:24)
2024-03-18T03:17:25.682604550Z     at listOnTimeout (node:internal/timers:573:17)
2024-03-18T03:17:25.682721851Z     at process.processTimers (node:internal/timers:514:7) 
2024-03-18T03:17:28.025486305Z ERROR ======= 2024-03-18 03:17:28: TypeError: Cannot read properties of undefined (reading 'service')
2024-03-18T03:17:28.025552306Z     at FP.service (/www/node_modules/total5/flowstream.js:625:8)
2024-03-18T03:17:28.025566106Z     at Timeout._onTimeout (/www/node_modules/total5/index.js:1136:23)
2024-03-18T03:17:28.025612606Z     at listOnTimeout (node:internal/timers:573:17)
2024-03-18T03:17:28.025618806Z     at process.processTimers (node:internal/timers:514:7) 
2024-03-18T03:18:28.045584220Z ERROR ======= 2024-03-18 03:18:28: TypeError: Cannot read properties of undefined (reading 'service')
2024-03-18T03:18:28.045671221Z     at FP.service (/www/node_modules/total5/flowstream.js:625:8)
2024-03-18T03:18:28.045683521Z     at Timeout._onTimeout (/www/node_modules/total5/index.js:1136:23)
2024-03-18T03:18:28.045687521Z     at listOnTimeout (node:internal/timers:573:17)
2024-03-18T03:18:28.045690421Z     at process.processTimers (node:internal/timers:514:7) 
2024-03-18T03:19:21.397921587Z ERROR ======= 2024-03-18 03:19:21: TypeError: Cannot read properties of undefined (reading 'flowstream')
2024-03-18T03:19:21.397982086Z     at process.<anonymous> (/www/node_modules/total5/flow-flowstream.js:1152:16)
2024-03-18T03:19:21.397992086Z     at process.emit (node:events:525:35)
2024-03-18T03:19:21.397997186Z     at emit (node:internal/child_process:944:14)
2024-03-18T03:19:21.398004286Z     at process.processTicksAndRejections (node:internal/process/task_queues:83:21) 
2024-03-18T03:19:28.082734253Z ERROR ======= 2024-03-18 03:19:28: TypeError: Cannot read properties of undefined (reading 'service')
2024-03-18T03:19:28.082770553Z     at FP.service (/www/node_modules/total5/flowstream.js:625:8)
2024-03-18T03:19:28.082784053Z     at Timeout._onTimeout (/www/node_modules/total5/index.js:1136:23)
2024-03-18T03:19:28.082797553Z     at listOnTimeout (node:internal/timers:573:17)
2024-03-18T03:19:28.082812353Z     at process.processTimers (node:internal/timers:514:7) 
2024-03-18T03:20:28.114562797Z ERROR ======= 2024-03-18 03:20:28: TypeError: Cannot read properties of undefined (reading 'service')
2024-03-18T03:20:28.114609697Z     at FP.service (/www/node_modules/total5/flowstream.js:625:8)
2024-03-18T03:20:28.114637297Z     at Timeout._onTimeout (/www/node_modules/total5/index.js:1136:23)
2024-03-18T03:20:28.114640497Z     at listOnTimeout (node:internal/timers:573:17)
2024-03-18T03:20:28.114643197Z     at process.processTimers (node:internal/timers:514:7) 
```

**Comment by yilativ** [comment]
Works when I do the pull from github repo directly... however this is happening everytime I do anything to the flow: 

```
ERROR ======= 2024-03-18 04:47:58: Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at Controller.flush (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:366:11)
    at Controller.html (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:218:7)
    at Controller.fallback (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:412:8)
    at Timeout._onTimeout (C:\api\totaljs\flow\flow\node_modules\total5\index.js:1170:11)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at Controller.flush (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:366:11)
    at Controller.html (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:218:7)
    at Controller.fallback (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:412:8)
    at Timeout._onTimeout (C:\api\totaljs\flow\flow\node_modules\total5\index.js:1170:11)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
ERROR ======= 2024-03-18 04:48:03: Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at Controller.flush (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:366:11)
    at Controller.html (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:218:7)
    at Controller.fallback (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:412:8)
    at Timeout._onTimeout (C:\api\totaljs\flow\flow\node_modules\total5\index.js:1170:11)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at Controller.flush (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:366:11)
    at Controller.html (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:218:7)
    at Controller.fallback (C:\api\totaljs\flow\flow\node_modules\total5\controller.js:412:8)
    at Timeout._onTimeout (C:\api\totaljs\flow\flow\node_modules\total5\index.js:1170:11)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by petersirka** [comment]
Hi. Hmm, it's something strange. If I pull and run `totalplatform/flow` image it works like a charm. Can you run it like this?

```bash
docker pull totalplatform/flow:latest    
docker run -p 8000:8000 totalplatform/flow
```

I tested it 5 minutes ago.

**Comment by petersirka** [comment]
Also, I tested it on Windows, and it works.

**Comment by yilativ** [comment]
I deleted the image/container and did new volumes... it works
I wonder if the CDN had an old version that I was connecting to with when the componenator was pulling components ... 

Thank you for checking and it works for me without any code change

![image](https://github.com/totaljs/flow/assets/1034910/3379a7c7-5503-4a22-877c-20417b4b208c)

**Comment by petersirka** [comment]
> I deleted the image/container and did new volumes... it works I wonder if the CDN had an old version that I was connecting to with when the componenator was pulling components ...
> 
> Thank you for checking and it works for me without any code change
> 
> ![image](https://private-user-images.githubusercontent.com/1034910/313730942-3379a7c7-5503-4a22-877c-20417b4b208c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzQ4MTAsIm5iZiI6MTcxMDc3NDUxMCwicGF0aCI6Ii8xMDM0OTEwLzMxMzczMDk0Mi0zMzc5YTdjNy01NTAzLTRhMjItODc3Yy0yMDQxN2I0YjIwOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMTUwODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmE5YmI1NjUzYWY2NTkwNTUxMzhiOWZhMTg2YTZkMDQyYTI5MDYzMTdmNTQ2Y2Q4M2IyMTEzY2QyYWIwYmU5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LS5mEvXzF9ad8QIzGIxq1-9cSmmASmrdCf_sElOiXAg)

Good question. The flow doesn't use external dependencies in the core, but maybe we made a mistake or something else. The important thing is that it works now.

**Comment by yilativ** [comment]
The CDN I was thinking about was this: 

![image](https://github.com/totaljs/flow/assets/1034910/92889ed9-8e1d-4897-b37d-613301713f3b)

**Comment by petersirka** [comment]
Yes, you're right. We changed a link to the repo for the "newest" Flow version due to backward compatibility. Good point, thank you.
