### ISSUE TITLE
TypeError: Cannot read property 'slug' of undefined

### ISSUE THREAD

**Issue by argmhz** [totaljs/flow#22]
Hi guys, can you tell me if i have done something wrong? 

 ```TypeError: Cannot read property 'slug' of undefined
node_1  |     at Object.FLOW.register (/home/app/tmp/flow.package/index.js:1162:16)
node_1  |     at Object.FLOW.execute (/home/app/tmp/flow.package/index.js:1639:7)
node_1  |     at Array.<anonymous> (/home/app/tmp/flow.package/index.js:1660:10)
node_1  |     at Array.wait.Array.waitFor (/home/app/node_modules/total.js/utils.js:4563:9)
node_1  |     at Immediate.next_wait (/home/app/node_modules/total.js/utils.js:4576:7)
node_1  |     at runCallback (timers.js:697:11)
node_1  |     at tryOnImmediate (timers.js:667:5)
node_1  |     at processImmediate (timers.js:649:5)
node_1  | ======= 2018-06-15 14:53:46: TypeError: Cannot read property 'slug' of undefined 

TypeError: Cannot read property 'slug' of undefined
node_1  |     at Object.FLOW.register (/home/app/tmp/flow.package/index.js:1162:16)
node_1  |     at Object.FLOW.execute (/home/app/tmp/flow.package/index.js:1639:7)
node_1  |     at Array.<anonymous> (/home/app/tmp/flow.package/index.js:1660:10)
node_1  |     at Array.wait.Array.waitFor (/home/app/node_modules/total.js/utils.js:4563:9)
node_1  |     at Immediate.next_wait (/home/app/node_modules/total.js/utils.js:4576:7)
node_1  |     at runCallback (timers.js:697:11)
node_1  |     at tryOnImmediate (timers.js:667:5)
node_1  |     at processImmediate (timers.js:649:5)```

**Comment by petersirka** [comment]
Hi @argmhz, there is a problem in some component. `.slug()` is used for obtaining of component name. Some component doesn't have this `exports.name` property. Try to look into the `/flow/` folder and check each component or send me the entire folder on my email, I'll find this problem.

**Comment by argmhz** [comment]
Hi @petersirka 

I think I maybe mix up with an old flow.package when i was building a dockerfile. got the new ones and now its working fine, 

thanks anyway :)
